version: '3.7'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rocketseat-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - segunda-network
    volumes:
      - db:/var/lib/mysql

  demo:
    container_name: demo
    build:
        context: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - segunda-network

networks:
  segunda-network:
    driver: bridge

volumes:
  db:
